#!/bin/bash

    echo -e "   INSTALANDO SERVIDOR PYTHON WS-EPRO"
    sleep 0.3
    echo

    # Download and install ws-epro
    download_and_install "https://docs.google.com/uc?export=download&id=1IbwfNpKpa1JzvXsDT-WgNpp5nWrklisG" "/usr/local/bin/ws-epro"

    # Download and install ws-epro service
    download_and_install "https://docs.google.com/uc?export=download&id=10hGKYNZUMHdr4y-ZxMr0wKQpj9zSQRkZ" "/etc/systemd/system/ws-epro.service"

    # Download and install ws-epro port script
    download_and_install "https://docs.google.com/uc?export=download&id=1h9QvOnXScplGTnfpbJ7KJDn4CDkwUKWa" "/usr/bin/ws-port"

    # Set port configurations
    wsopenssh=8080
    openssh=22
    WS_DIR="/usr/local/etc/ws-epro"
    [ -d "$WS_DIR" ] && rm -rf "$WS_DIR"
    sleep 0.3
    mkdir -p "$WS_DIR"

    # Create configuration file
    cat <<EOF > "$WS_DIR/config.yml"
# verbose level 0=info, 1=verbose, 2=very verbose
verbose: 0
listen:
##openssh
- target_host: 127.0.0.1
##portopenssh
  target_port: $openssh
##wsopenssh
  listen_port: $wsopenssh
EOF

    chmod +x "$WS_DIR/config.yml"

    # Enable and start ws-epro service
    systemctl enable ws-epro
    systemctl start ws-epro

    sleep 0.3
    enc_darnix
    echo
    print_center -ama "CONFIGURACIÓN EXITOSA WS EPRO INSTALADO"
    echo -e "${YELLOW}             Puerto Local SSH: ${GREEN}$openssh${RESET}"
    echo -e "${YELLOW}             Puerto Phyton: ${GREEN}$wsopenssh${RESET}"
    }

# Function to download and install a file
download_and_install() {
    local download_url=$1
    local install_path=$2

    wget -q --show-progress --load-cookies /tmp/cookies.txt "$download_url" -O "$install_path" && rm -rf /tmp/cookies.txt
chmod +x "$install_path"

}

# Function to modify WS-EPRO port
