#!/bin/bash

fun_bar() {
    CMD[0]="$1"
    CMD[1]="$2"
    colors=("31" "32" "33" "34" "35")  # Lista de códigos de color ANSI para puntos
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${CMD[0]} -y >/dev/null 2>&1
        ${CMD[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne " ${grs}Instalación ${gry}- ${grs}["
    while true; do
        for ((i = 0; i < 11; i++)); do
            color_index=$(( $i % ${#colors[@]} ))  # Calcula el índice del color
            color="\033[${colors[$color_index]}m"  # Obtiene el código de color ANSI
            echo -ne "${color}•${reset}"  # Muestra el punto con el color
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "${grs}]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne " ${grs}Instalación ${gry}- ${grs}["
    done
    echo -e "${grs}]${gry} - ${gr}Finalizado !${gry}"
    tput cnorm
}

fun_bar
